// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.dhis2_flutter_test_impl

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object Dhis2ApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is Dhis2PigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class Dhis2PigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginCredentials (
  val serverUrl: String,
  val username: String,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginCredentials {
      val serverUrl = pigeonVar_list[0] as String
      val username = pigeonVar_list[1] as String
      val password = pigeonVar_list[2] as String
      return LoginCredentials(serverUrl, username, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serverUrl,
      username,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LoginCredentials) {
      return false
    }
    if (this === other) {
      return true
    }
    return Dhis2ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginResult (
  val username: String,
  val successMessage: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginResult {
      val username = pigeonVar_list[0] as String
      val successMessage = pigeonVar_list[1] as String
      return LoginResult(username, successMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      username,
      successMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LoginResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return Dhis2ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class Dhis2ApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginCredentials.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LoginCredentials -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LoginResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface Dhis2LoginApi {
  fun login(credentials: LoginCredentials, callback: (Result<LoginResult>) -> Unit)
  fun isUserLoggedIn(callback: (Result<Boolean>) -> Unit)
  fun logout(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by Dhis2LoginApi. */
    val codec: MessageCodec<Any?> by lazy {
      Dhis2ApiPigeonCodec()
    }
    /** Sets up an instance of `Dhis2LoginApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: Dhis2LoginApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dhis2_flutter_test_impl.Dhis2LoginApi.login$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as LoginCredentials
            api.login(credentialsArg) { result: Result<LoginResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Dhis2ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Dhis2ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dhis2_flutter_test_impl.Dhis2LoginApi.isUserLoggedIn$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isUserLoggedIn{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Dhis2ApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(Dhis2ApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dhis2_flutter_test_impl.Dhis2LoginApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(Dhis2ApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(Dhis2ApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
